INSERT INTO `books`(`PublishYear`, `Title`, `Author`) VALUES ("2003","Animal Farm","George Orwell");
INSERT INTO `books`(`PublishYear`, `Title`, `Author`) VALUES ("1999","Gone With The Wind","Margaret Mitchel");
INSERT INTO `books`(`PublishYear`, `Title`, `Author`) VALUES ("2004","Harry Potter and the Order of the Phoenix","J.K. Rowling");
INSERT INTO `books`(`PublishYear`, `Title`, `Author`) VALUES ("2000","Pride and Prejudice","Jane Austen");
INSERT INTO `books`(`PublishYear`, `Title`, `Author`) VALUES ("2006","The Book Thief","Markus Zusak");
INSERT INTO `books`(`PublishYear`, `Title`, `Author`) VALUES ("2002","The Chronicles of Narnia","C.S. Lewis");
INSERT INTO `books`(`PublishYear`, `Title`, `Author`) VALUES ("2012","The Fault In Our Stars","John Green");
INSERT INTO `books`(`PublishYear`, `Title`, `Author`) VALUES ("2008","The Hunger Games","Suzanne Collins");
INSERT INTO `books`(`PublishYear`, `Title`, `Author`) VALUES ("2006","To Kill A Mockingbird","Harper Lee");
INSERT INTO `books`(`PublishYear`, `Title`, `Author`) VALUES ("2006","Twilight","Stephenie Meyer");